[package]
name = "alert-deleter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["env", "derive"] }
ctrlc = "3.4.5"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
kube = { version = "0.96.0", features = ["derive"] }
log = "0.4.22"
reqwest = { version = "0.12.8", features = ["json"] }
serde = "1.0.213"
simple_logger = "5.0.0"
tokio = { version = "1.41.0", features = ["full"] }
