[package]
name = "alert-deleter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["env", "derive"] }
ctrlc = "3.4.5"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = { version = "0.98.0", features = ["derive"] }
log = "0.4.25"
reqwest = { version = "0.12.9", features = ["json"] }
serde = "1.0.217"
simple_logger = "5.0.0"
tokio = { version = "1.43.0", features = ["full"] }
